#!/bin/bash

# Google DOCS extension for todotxt
# First release: 7/10/2011
# Author: Amaury Decrême - amaury.decreme at gmail.com
# Licence: GPL http://www.gnu.org/copyleft/gpl.html
#
# With this add-on you can now sync your todo with Google Docs
# Therefore, sharing your todos with people is now possible
# This also let you sync your todos with aNotes on iPhone for example
# Or you can display your Google managed todos on your terminal or desktop
#
# We explicitly omit the todotxt priority when Google Docs syncing
#

function firstrun() {
	echo "Welcome, for happiness verify the following:"
	echo "- Google Docs account"
	echo "- todo folder in docs (name stored in .docs file)"
	echo "- Google CL installed (visit http://code.google.com/p/googlecl)"
	echo "- Google CL with oAuth configured (run 'google docs list')"
}

function usage() {
	echo "Usage: $TODO_SH docs <option>"
	echo
	echo "Options:"
	echo "	pull	Pull todo from Google docs"
	echo "	push 	Push todo to Google docs"
	echo "	help	This help"
	echo
	firstrun
}

function init() {
	DOCS=$(dirname $0)/.docs

	if [ ! -f "$DOCS" ] ; then
		firstrun
		echo "Type CTRL-C now if something is not ok"
		echo
		echo "Please, what is yout todo folder name in docs:"
		read f
		echo $f > "$DOCS"
		echo "Hurray, docs pull push should work now."
	fi

	FOLDER=$(cat "$DOCS")
	if [ -z "$FOLDER" ] ; then
		echo 'TODO folder empty'
		exit 1
	fi
	

	google docs list --folder "$FOLDER" 2>&1|awk -F, '{print $1}' > $tmpf
	if [ `grep 'No folder found' $tmpf|wc -l` -ne 0 ] ; then
		echo "$FOLDER not found"
		rm -f $tmpf 
		exit 1
	fi
}

if [ $# -ne 2 ] ; then
	usage
	exit 0
fi

tmpf="/tmp/$(basename $0).$$"
shift

case $1 in
'pull' )
	init $tmpf
	cat $tmpf|while read title ; do
		regexp=^$title$
		if [ `sed 's/^(.) //' "$TODO_FILE"|grep "$regexp"|wc -l` -eq 0 ] ; then
			$TODO_DIR/$TODO_SH add "$title"
		fi
	done
	sed 's/^(.) //' "$TODO_FILE"|while read l; do
		[ -z "$l" ] && continue
		regexp=^$l$
		if [ `grep "$regexp" $tmpf|wc -l` -eq 0 ] ; then
			tmpf2="/tmp/$(basename $0).$$2"
			grep -v "$l" "$TODO_FILE" > $tmpf2 && rm "$TODO_FILE" && cp $tmpf2 "$TODO_FILE" && rm -f $tmpf2
			echo "$l deleted in todo"
		fi
	done
	;;
'push' )
	init $tmpf
	sed 's/^(.) //' "$TODO_FILE"|while read l; do
		[ -z "$l" ] && continue
		regexp=^$l$
		if [ `grep "$regexp" $tmpf|wc -l` -eq 0 ] ; then
			echo "adding $l in docs\n"
			touch /tmp/$$.$l
			google docs upload --src "/tmp/$$.$l" --title "$l" --folder "$FOLDER" > /dev/null
			[ $? -eq 0 ] ; echo "$l added in docs"
			rm -f /tmp/$$.$l
		fi
	done
	
	cat $tmpf|while read title ; do
		regexp=^$title$
		if [ `sed 's/^(.) //' "$TODO_FILE"|grep "$regexp"|wc -l` -eq 0 ] ; then
			google docs delete --title "$title" --folder "$FOLDER" > /dev/null <<EOF
y
EOF
			[ $? -eq 0 ] ; echo "$title deleted in docs"
		fi
	done
	;;
'help' )
	usage
	;;
*)
	echo 'Unknown command. Type <todo> docs help'
	;;
esac

rm -f $tmpf

