name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  test:
    strategy:
      matrix:
        platform:
        - ubuntu-latest
        - ubuntu-22.04
        - macos-latest
        - macos-15
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v7
    - run: make
    - run: |
        make test
        modifiedFiles=$(git status --porcelain)
        if [ -n "$modifiedFiles" ]; then
          printf >&2 'ERROR: The following files were modified during the test:\n%s\n' "$modifiedFiles"
          exit 1
        fi
    - run: make dist
    - run: make disttest
    - run: sudo make install
    - run: sudo make uninstall
    - run: sudo make clean
