name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  test:
    strategy:
      matrix:
        platform:
        - ubuntu-latest
        - ubuntu-22.04
        - macos-latest
        - macos-15
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v7
    - run: make
    - run: make test
    - run: make dist
    - run: make disttest
    - run: sudo make install
    - run: sudo make uninstall
    - run: sudo make clean
